apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaletestapp
  labels:
    tier: scaletestapp
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: scaletestapp
      app: scaletestapp
  template:
    metadata:
      labels:
        tier: scaletestapp
        app: scaletestapp
    spec:
      containers:
      - name: scaletestapp
        image: shestera/scaletestapp
        resources:
          limits:
            memory: "30Mi"
          requests:
            memory: "30Mi"
        ports:
        - containerPort: 8080
          protocol: TCP


          
